
// This file has been generated by the GUI designer. Do not modify.
namespace IERG3080
{
	public partial class MainWindow
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.Label label7;
		
		private global::Gtk.VBox vbox4;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.ComboBox accountNum;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.ComboBox accountType;
		
		private global::Gtk.VBox vbox6;
		
		private global::Gtk.HBox hbox5;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.Entry deposit;
		
		private global::Gtk.VBox vbox9;
		
		private global::Gtk.HBox hbox6;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.Entry withdraw;
		
		private global::Gtk.HBox hbox7;
		
		private global::Gtk.Label label9;
		
		private global::Gtk.Label balance;
		
		private global::Gtk.HBox hbox8;
		
		private global::Gtk.Button button1;
		
		private global::Gtk.Button button2;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget IERG3080.MainWindow
			this.Name = "IERG3080.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child IERG3080.MainWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Bank of Group 13");
			this.vbox3.Add (this.label7);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.label7]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Account Nmuber");
			this.hbox1.Add (this.label3);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label3]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.accountNum = global::Gtk.ComboBox.NewText ();
			this.accountNum.Name = "accountNum";
			this.hbox1.Add (this.accountNum);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.accountNum]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			this.vbox4.Add (this.hbox1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox1]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Account Type");
			this.hbox2.Add (this.label4);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label4]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.accountType = global::Gtk.ComboBox.NewText ();
			this.accountType.Name = "accountType";
			this.hbox2.Add (this.accountType);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.accountType]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			this.vbox4.Add (this.hbox2);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox2]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Deposit");
			this.hbox5.Add (this.label1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label1]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.deposit = new global::Gtk.Entry ();
			this.deposit.CanFocus = true;
			this.deposit.Name = "deposit";
			this.deposit.IsEditable = true;
			this.deposit.InvisibleChar = '●';
			this.hbox5.Add (this.deposit);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.deposit]));
			w9.Position = 1;
			this.vbox6.Add (this.hbox5);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox5]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			this.vbox4.Add (this.vbox6);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.vbox6]));
			w11.Position = 2;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.vbox9 = new global::Gtk.VBox ();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Withdraw");
			this.hbox6.Add (this.label2);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label2]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.withdraw = new global::Gtk.Entry ();
			this.withdraw.CanFocus = true;
			this.withdraw.Name = "withdraw";
			this.withdraw.IsEditable = true;
			this.withdraw.InvisibleChar = '●';
			this.hbox6.Add (this.withdraw);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.withdraw]));
			w13.Position = 1;
			this.vbox9.Add (this.hbox6);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.hbox6]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			this.vbox4.Add (this.vbox9);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.vbox9]));
			w15.Position = 3;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Balance");
			this.hbox7.Add (this.label9);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.label9]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.balance = new global::Gtk.Label ();
			this.balance.Name = "balance";
			this.balance.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
			this.hbox7.Add (this.balance);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.balance]));
			w17.Position = 1;
			w17.Expand = false;
			w17.Fill = false;
			this.vbox4.Add (this.hbox7);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox7]));
			w18.Position = 4;
			w18.Expand = false;
			w18.Fill = false;
			this.vbox3.Add (this.vbox4);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.vbox4]));
			w19.Position = 1;
			w19.Expand = false;
			w19.Fill = false;
			this.vbox1.Add (this.vbox3);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox3]));
			w20.Position = 0;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.button1 = new global::Gtk.Button ();
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseUnderline = true;
			this.button1.Label = global::Mono.Unix.Catalog.GetString ("Save");
			this.hbox8.Add (this.button1);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.button1]));
			w21.Position = 0;
			w21.Expand = false;
			w21.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.button2 = new global::Gtk.Button ();
			this.button2.CanFocus = true;
			this.button2.Name = "button2";
			this.button2.UseUnderline = true;
			this.button2.Label = global::Mono.Unix.Catalog.GetString ("Withdraw");
			this.hbox8.Add (this.button2);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.button2]));
			w22.Position = 1;
			w22.Expand = false;
			w22.Fill = false;
			this.vbox1.Add (this.hbox8);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox8]));
			w23.Position = 1;
			w23.Expand = false;
			w23.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		}
	}
}
